"""empty message

Revision ID: 03c1a5760c79
Revises: 165c00a0c593
Create Date: 2021-08-03 15:24:59.517146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c1a5760c79'
down_revision = '165c00a0c593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_mosaic_user', 'ad_user', ['mosaic_user'])
    op.create_unique_constraint('uq_mapping', 'ad_mapping', ['user_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE ad_user DROP KEY uq_mosaic_user;')
    op.execute('ALTER TABLE ad_mapping DROP KEY uq_mapping;')
    # ### end Alembic commands ###
