"""empty message

Revision ID: 132ebebacd6a
Revises: 10599284cae5
Create Date: 2023-04-17 15:20:23.253839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132ebebacd6a'
down_revision = '1edb758bc414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nb_data_snapshot', 'access_type',
                    type_=sa.String(length=50),
                    existing_nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
