"""create new column for git_proxy in nb_git_repository table

Revision ID: 1408ae3e05ed
Revises: 732f50c5c780
Create Date: 2023-10-04 11:40:37.982837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1408ae3e05ed'
down_revision = '732f50c5c780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nb_git_repository', sa.Column('proxy_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nb_git_repository', 'proxy_details')
    # ### end Alembic commands ###
