"""empty message

Revision ID: 15a343de269f
Revises: 4af8869170c4
Create Date: 2021-03-13 12:26:11.773274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a343de269f'
down_revision = '4af8869170c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nb_docker_image", sa.Column("git_macros_config", sa.JSON()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nb_docker_image", "git_macros_config")

    # ### end Alembic commands ###
