"""empty message

Revision ID: 1edb758bc414
Revises: 91607552aab4
Create Date: 2023-04-21 12:52:18.440688

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1edb758bc414'
down_revision = 'a9b4edede4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cp_plugins', sa.Column('alert_parameters', sa.JSON, default={}))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cp_plugins', 'alert_parameters')
    # ### end Alembic commands ###
