"""Password Column size 60->255
Revision ID: 3ab985242bea
Revises: 15a343de269f
Create Date: 2021-03-22 15:16:46.738209

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3ab985242bea'
down_revision = '15a343de269f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nb_git_repository', 'password',
                        existing_type=sa.String(length=60),
                        type_=sa.Text,
                        existing_nullable=False)
    #


def downgrade():
    op.alter_column('nb_git_repository', 'password',
                        existing_type=sa.Text,
                        type=sa.String(length=60),
                        existing_nullable=False)
