"""empty message

Revision ID: 44bab837f480
Revises: 67e1d655b98f
Create Date: 2021-03-02 17:30:19.212937

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '44bab837f480'
down_revision = '67e1d655b98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nb_git_repository', sa.Column('created_by', sa.String(100), nullable=True))
    op.add_column('nb_git_repository', sa.Column('created_on', sa.DateTime, default=datetime.utcnow, nullable=True))
    op.add_column('nb_git_repository', sa.Column('last_modified_by', sa.String(100), nullable=True))
    op.add_column('nb_git_repository',
                  sa.Column('last_modified_on', sa.DateTime, default=datetime.utcnow, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nb_git_repository', 'created_by')
    op.drop_column('nb_git_repository', 'created_on')
    op.drop_column('nb_git_repository', 'last_modified_by')
    op.drop_column('nb_git_repository', 'last_modified_on')
    # ### end Alembic commands ###
