"""empty message

Revision ID: 4af8869170c4
Revises: 44bab837f480
Create Date: 2021-02-23 15:56:41.570029

"""
from alembic import op
import sqlalchemy as sa
from notebooks_api import get_db_type
from notebooks_api.db_utility import drop_custom_type_enum

# revision identifiers, used by Alembic.
revision = '4af8869170c4'
down_revision = '44bab837f480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nb_data_snapshot',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('snapshot_name', sa.String(length=200), nullable=False),
    sa.Column('container', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('git_repo', sa.String(length=100), nullable=True),
    sa.Column('commit_id', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('snapshot_path', sa.String(length=200), nullable=True),
    sa.Column('access_type', sa.Enum('OWNER', 'CONTRIBUTOR', 'VIEWER', name="NBType"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nb_template_status', sa.Column('input', sa.String(length=200), nullable=True))
    op.add_column('nb_template_status', sa.Column('output', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nb_data_snapshot')
    drop_custom_type_enum(sa.Enum('OWNER', 'CONTRIBUTOR', 'VIEWER', name='NBType'))
    op.drop_column('nb_template_status', 'input')
    op.drop_column('nb_template_status', 'output')
    # ### end Alembic commands ###
