"""empty message

Revision ID: 694891f74d98
Revises: 
Create Date: 2018-11-14 14:48:02.055423

"""
from alembic import op
import sqlalchemy as sa
from notebooks_api import get_db_type
from notebooks_api.db_utility import drop_custom_type_enum


# revision identifiers, used by Alembic.
revision = '694891f74d98'
down_revision = None
branch_labels = None
depends_on = None

db_type = get_db_type()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nb_resource',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('cpu', sa.String(length=10), nullable=False),
    sa.Column('mem', sa.String(length=10), nullable=False),
    sa.Column('extra', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nb_docker_image',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('type', sa.Enum('PRE_BUILD', 'CUSTOM_BUILD', name="NBType"), nullable=True),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('docker_url', sa.String(length=200), nullable=False),
    sa.Column('pip_packages', sa.Text(), nullable=True),
    sa.Column('conda_packages', sa.Text(), nullable=True),
    sa.Column('docker_file', sa.Text(), nullable=True),
    sa.Column('base_image_id', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['base_image_id'], ['nb_docker_image.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['nb_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nb_docker_image_tag',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('tag', sa.String(length=200), nullable=False),
    sa.Column('docker_image_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['docker_image_id'], ['nb_docker_image.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nb_notebook',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('resource_id', sa.String(length=60), nullable=True),
    sa.Column('docker_image_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['docker_image_id'], ['nb_docker_image.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['nb_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nb_notebook_pod',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'RUNNING', 'STOPPING', name="NBPodStatus"), nullable=True),
    sa.Column('notebook_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['nb_notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nb_notebook_pod_archive',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'RUNNING', 'STOPPING', name="NBPodArchiveStatus"), nullable=True),
    sa.Column('notebook_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['nb_notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nb_notebook_tag',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=60), nullable=False),
    sa.Column('tag', sa.String(length=200), nullable=False),
    sa.Column('notebook_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['nb_notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nb_pypi_package',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nb_pypi_package_version',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('package_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['nb_pypi_package.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nb_pypi_package_version')
    op.drop_table('nb_pypi_package')
    op.drop_table('nb_docker_image_tag')
    op.drop_table('nb_notebook_tag')
    op.drop_table('nb_notebook_pod_archive')
    op.drop_table('nb_notebook_pod')
    op.drop_table('nb_notebook')
    op.drop_table('nb_docker_image')
    op.drop_table('nb_resource')
    drop_custom_type_enum(sa.Enum('STARTING', 'RUNNING', 'STOPPING', name='NBPodStatus'))
    drop_custom_type_enum(sa.Enum('PRE_BUILD', 'CUSTOM_BUILD', name='NBType'))
    drop_custom_type_enum(sa.Enum('STARTING', 'RUNNING', 'STOPPING', name='NBPodArchiveStatus'))

    # ### end Alembic commands ###
