"""empty message

Revision ID: 70bfd092da16
Revises: 1e16fef49797
Create Date: 2021-05-06 17:09:01.738053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bfd092da16'
down_revision = '1e16fef49797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_user",
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('user_name', sa.String(length=120), nullable=False),
        sa.Column('mosaic_user', sa.String(120), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table(
        "ad_group",
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('group_name', sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table(
        "ad_mapping",
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_user')
    op.drop_table('ad_group')
    op.drop_table('ad_mapping')
    # ### end Alembic commands ###
