"""Added new table for storing pod names

Revision ID: 732f50c5c780
Revises: 8310ef1d572d
Create Date: 2023-06-14 16:51:17.095767

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '732f50c5c780'
down_revision = '8310ef1d572d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nb_pod_resource_alerts',
                    sa.Column('id', sa.String(length=60), nullable=False),
                    sa.Column('new_pods', sa.String(length=500), nullable=True),
                    sa.Column('existing_pods', sa.String(length=500), nullable=True),
                    sa.Column('usage_percent', sa.Float(), nullable=True),
                    sa.Column('resource_type', sa.String(length=100), nullable=True),
                    sa.Column('project_id', sa.String(length=500), nullable=True),
                    sa.Column('project_name', sa.String(length=500), nullable=True),
                    sa.Column('template_name', sa.String(length=500), nullable=True),
                    sa.Column('template_id', sa.String(length=500), nullable=True),
                    sa.Column('user_name', sa.String(length=500), nullable=True),
                    sa.Column('alert_status', sa.Boolean(), nullable=False)
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nb_pod_resource_alerts')
    # ### end Alembic commands ###
