"""empty message

Revision ID: 91607552aab4
Revises: f26932f1959a
Create Date: 2023-04-04 19:22:33.256671

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '91607552aab4'
down_revision = 'f26932f1959a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cp_plugin_settings', sa.Column('object_info', sa.JSON, default={}, nullable=False))

    op.drop_column('cp_plugin_settings', 'project_id')
    op.drop_column('cp_plugin_settings', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cp_plugin_settings', 'object_info')

    op.add_column('cp_plugin_settings', sa.Column('project_id', sa.String(length=100), nullable=False))
    op.add_column('cp_plugin_settings', sa.Column('user_id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###
