"""adding spcs_data column

Revision ID: a30e085a2025
Revises: e10e096a5820
Create Date: 2023-12-15 11:22:39.979352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30e085a2025'
down_revision = 'e10e096a5820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nb_template_status', sa.Column('spcs_data', sa.JSON, default={}))
    op.add_column('nb_docker_image', sa.Column('spcs_data', sa.JSON, default={}))
    op.execute("""ALTER TYPE "NBType" add value IF NOT EXISTS 'PRE_BUILD_SPCS';""")
    op.execute("""ALTER TYPE "NBType" add value IF NOT EXISTS 'CUSTOM_BUILD_SPCS';""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nb_template_status', 'spcs_data')
    op.drop_column('nb_docker_image', 'spcs_data')
    # ### end Alembic commands ###