"""add snapshot_input_path in table nb_data_snapshot

Revision ID: c99939b65b7e
Revises: 790960cd69fe
Create Date: 2021-10-27 13:48:35.449892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99939b65b7e'
down_revision = '790960cd69fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nb_data_snapshot', sa.Column('snapshot_input_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nb_notebook', 'snapshot_input_path')
    # ### end Alembic commands ###
