"""empty message

Revision ID: e10e096a5820
Revises: 1408ae3e05ed
Create Date: 2023-11-06 11:25:39.979352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10e096a5820'
down_revision = '1408ae3e05ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cp_plugins',sa.Column('package_name', sa.String(length=100), nullable=True))
    op.add_column('cp_plugins',sa.Column('package_version', sa.String(length=100), nullable=True))
    op.add_column('cp_plugins',sa.Column('model_required', sa.Boolean(), nullable=True,default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cp_plugins', 'package_name')
    op.drop_column('cp_plugins', 'package_version')
    op.drop_column('cp_plugins', 'model_required')