apiVersion: batch/v1
kind: Job
metadata:
  name: {jobName}
  namespace: {namespace}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: {jobName}
        image: {image}
        imagePullPolicy: Always
        command: {command}
        env: {envVar}
      imagePullSecrets:
      - name: {image_pull_secret}
      restartPolicy: Never
